### ISSUE TITLE
fat jar

### ISSUE THREAD

**Issue by scale-logic** [malinochkaaa/transaction-check#1]
1. clean log4j jar in project
2. project -> plugin.sbt  -> addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.0.0")
3. assemblyMergeStrategy in assembly := {
  case PathList("META-INF", _*) => MergeStrategy.discard
  case _                        => MergeStrategy.first
}
4. set clean
5. set assembly

**Comment by malinochkaaa** [comment]
Сборка завершена.
